version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: sentiment-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: sentiment-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true